server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/battleship}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# Custom application properties (not Spring Boot standard properties)
jwt:
  secret: ${JWT_SECRET:please_change_me_this_is_a_very_long_secret_key_for_jwt_signing}
  expiration: ${JWT_EXPIRATION:86400}

openai:
  api:
    key: ${OPENAI_API_KEY:}

room:
  empty:
    ttl: ${ROOM_EMPTY_TTL_SEC:60}
  cleanup:
    interval: 30000

turn:
  timeout:
    sec: ${TURN_TIMEOUT_SEC:30}

reconnect:
  grace:
    sec: ${RECONNECT_GRACE_SEC:60}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info
    "[app.battleship]": debug
